services:
  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: leishimaniaapp-db
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

#  rabbit:
#    restart: always
#    image: rabbitmq:latest
#    network_mode: host
#    env_file:
#      - .env
#    volumes:
#      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
#      - ./data/rabbitmq/log/:/var/log/rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      interval: 30s
#      timeout: 30s
#      retries: 3

#  worker:
#    restart: always
#    platform: linux/x86_64
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    command: celery -A leishimaniaapp worker -l info --concurrency=2
#    network_mode: host
#    env_file:
#      - .env
#    depends_on:
#      - rabbit
#      - postgres
#    volumes:
#      - ./staticfiles:/code/staticfiles
#      - ./media:/code/media
#    mem_limit: 1000m

  web:
    platform: linux/x86_64
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
#      - rabbit
    ports:
      - 8080:8080
    entrypoint: /code/scripts_infra/entrypoint.sh
    volumes:
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media

  nginx:
    restart: always
    image: nginx:alpine
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - web

volumes:
  data:
  staticfiles:
  media:
