version: "3.9"
services:

  postgres:
    image: postgres:13-alpine
    container_name: leishimaniaapp-db
    environment:
      POSTGRES_USER: leishimaniaapp
      POSTGRES_PASSWORD: leishimaniaapp
      POSTGRES_DB: leishimaniaapp
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5440:5432

  rabbit:
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/log/:/var/log/rabbitmq

  worker:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A leishimaniaapp worker -l info
    env_file:
      - .env
    depends_on:
      - rabbit
  web:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
        - .env
    ports:
        - 80:80
        - 8000:80
    depends_on:
        - postgres
        - rabbit
    command: gunicorn leishimaniaapp.wsgi:application --bind gunicorn leishimaniaapp.wsgi -c app/gunicorn.conf.py --log-level warning -b 0.0.0.0:80

volumes:
  data: