version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: leishimaniaapp-db
    environment:
      POSTGRES_USER: leishimaniaapp
      POSTGRES_PASSWORD: leishimaniaapp
      POSTGRES_DB: leishimaniaapp
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5440:5432

  rabbit:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/log/:/var/log/rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A leishimaniaapp worker -l info --concurrency=2
    env_file:
      - .env
    depends_on:
      - rabbit
      - postgres
    volumes:
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media

  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8080:80
    depends_on:
      - postgres
      - rabbit
    entrypoint: /code/scripts_infra/entrypoint.sh
    volumes:
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media


volumes:
  data:
  staticfiles:
  media: