version: "3.3"
services:

  postgres:
    image: postgres:13-alpine
    container_name: leishimaniaapp-db
    environment:
      POSTGRES_USER: leishimaniaapp
      POSTGRES_PASSWORD: leishimaniaapp
      POSTGRES_DB: leishimaniaapp
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5440:5432
