# Generated by Django 4.2.13 on 2024-06-01 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Indentificador",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome do Laboratório"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participantes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratório",
                "verbose_name_plural": "Laboratórios",
            },
        ),
        migrations.CreateModel(
            name="MicroscopeSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Indentificador",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "slide_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome da lâmina"
                    ),
                ),
                (
                    "prediction_class",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Classe de previsão",
                    ),
                ),
                (
                    "prediction_percentage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Porcentagem de previsão"
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slides",
                        to="microscope_slide.laboratory",
                        verbose_name="Laboratório",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="microscope_slides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lâmina de microscópio",
                "verbose_name_plural": "Lâminas de microscópio",
                "ordering": ["slide_name"],
            },
        ),
        migrations.CreateModel(
            name="MicroscopeImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Indentificador",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="microscope_images/", verbose_name="Imagem"
                    ),
                ),
                (
                    "prediction_class",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Classe de previsão",
                    ),
                ),
                (
                    "prediction_percentage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Porcentagem de previsão"
                    ),
                ),
                (
                    "microscope_slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="microscope_slide.microscopeslide",
                        verbose_name="Lâmina de microscópio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem de microscópio",
                "verbose_name_plural": "Imagens de microscópio",
                "ordering": ["microscope_slide__slide_name"],
            },
        ),
    ]
