# Generated by Django 4.2.13 on 2025-03-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microscope_slide", "0004_microscopeimage_image_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microscopeslide",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("inception", "LV Humana"),
                    ("yolo", "LV Canina"),
                    ("none", "Nenhuma"),
                ],
                default="yolo",
                max_length=10,
                verbose_name="Tipo de Classificação",
            ),
        ),
    ]
